### ISSUE TITLE
hunt you in the company building

### ISSUE THREAD

**Issue by Spark61** [notsparble/facelessstalker#1]
the enemy hunts you when you are on the company moon, even though no monsters can actually spawn there

**Comment by Cracko298** [comment]
Their is no AI pathfinding on the company moon by defualt or added in this Mod.

Another mod must be to blame that adds Pathfinding to the Company Moon.

**Comment by notsparble** [comment]
As Cracko said, you are probably using a mod that adds a navmesh to the company moon, which would allow slenderman to spawn there
