### ISSUE TITLE
Pages Spawn Level config not respected

### ISSUE THREAD

**Issue by PiporGames** [notsparble/facelessstalker#2]
When Pages Spawn Level is set to "Modded", pages still spawn on vanilla moons.

**Comment by Cracko298** [comment]
I think the option is to include Modded Moons.

**Comment by dopadream** [comment]
Can confirm this option just doesn't work. Tried setting it to march only and it generates on every level regardless

**Comment by notsparble** [comment]
has been fixed with the new spawning config. You can now individually set the page spawn weight for each moon, including modded ones.
