### ISSUE TITLE
v50 error

### ISSUE THREAD

**Issue by LimerBoy** [notsparble/facelessstalker#4]
Game version v50
Mod version 1.1.3

but getting this error:
`
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SlendermanMod.SlendermanEnemyAI.Update () (at <611cedae329945c8a96010e6f83172e7>:IL_001C)
`

**Comment by notsparble** [comment]
Thanks for the report, when exactly did this happen? Did you pick up a page, did Slenderman start chasing you, did you collide with Slenderman?

**Comment by LimerBoy** [comment]
sorry, didn't saw ur message. Bug was fixed in latest updates.
